### ISSUE TITLE
Why this issue ?

### ISSUE THREAD

**Issue by fahadmehar** [dimitriwalters/github-lang-stats#1]
Can't load modules stats: /home/Statistics/eggdrop/modules/stats.so: wrong ELF class: ELFCLASS32
Can't load modules gseen: /home/Statistics/eggdrop/modules/gseen.so: wrong ELF class: ELFCLASS32

And I have load all the modules correctly.

**Comment by dimitriwalters** [comment]
I'm pretty sure this issue is for the wrong project: https://github.com/florian-sander/gseen.mod/issues/7

Closing this :)

**Comment by fahadmehar** [comment]
What? I didn't get you.

**Comment by dimitriwalters** [comment]
Your issue isn't relevant to this (dimitriwalters/github-lang-stats) repository
